const data=window.APP_DATA,$=id=>document.getElementById(id);let selected='all',current=data[0];
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
data.forEach(u=>{const o=document.createElement('option');o.value=u.id;o.textContent=u.id+' · '+u.title;$('lesson').append(o)});
function pairHTML(p,i,question=false){return `<article class="pair"><div class="pair-top"><span>${question?'題目與選項':'中英對照'} · ${String(i+1).padStart(2,'0')}</span><button class="speak" type="button">▶ 朗讀</button></div><p class="en" lang="en">${esc(p.en)}</p><p class="zh">${esc(p.zh)}</p>${p.answer?`<p class="answer">答案：${esc(p.answer)}</p>`:''}</article>`;}
function render(){current=data.find(u=>u.id===$('lesson').value)||data[0];selected='all';$('unit-label').textContent=current.id+' · 教師卷 × 解答與中譯';$('unit-title').textContent=current.title;['merged','teacher','answers'].forEach(k=>$(k).href=`downloads/${current.id}-${k}.docx`);$('categories').innerHTML='<button data-cat="all" class="active">全部題型</button>'+current.sections.map((s,i)=>`<button data-cat="${i}">${esc(s.category)}</button>`).join('');
$('content').innerHTML=current.sections.map((s,i)=>`<section class="section" data-index="${i}"><h3 class="section-title">${esc(s.category)}</h3>${s.note?`<p class="notice">${esc(s.note)}</p>`:''}${s.pairs.map((p,n)=>pairHTML(p,n)).join('')}${s.questions?.length?'<h4>題目與選項對照</h4>'+s.questions.map((p,n)=>pairHTML(p,n,true)).join(''):''}<details class="source"><summary>查看本題型原題與答案</summary><h4>教師卷原題</h4><pre>${esc(s.sourceTeacher.join('\n'))}</pre><h4>原卷解答</h4><pre>${esc((s.sourceAnswer||[]).join('\n'))}</pre></details></section>`).join('');
$('original-content').innerHTML='<h3>完整教師卷</h3><pre>'+esc(current.teacher.join('\n'))+'</pre><h3>完整解答與中譯</h3><pre>'+esc(current.answer.join('\n'))+'</pre>';
$('search').value='';filter();history.replaceState(null,'','#'+current.id);}
function filter(){const q=$('search').value.trim().toLowerCase();let n=0;document.querySelectorAll('.section').forEach(s=>{const allowed=selected==='all'||selected===s.dataset.index;let visible=0;s.querySelectorAll('.pair').forEach(p=>{p.hidden=!allowed||!p.textContent.toLowerCase().includes(q);if(!p.hidden){n++;visible++;}});s.hidden=!allowed||!visible;s.querySelectorAll('.source').forEach(d=>d.hidden=!!q)});$('count').textContent=`本課目前顯示 ${n} 組中英對照`;$('empty').hidden=n>0;}
$('lesson').onchange=()=>{stopReading();render()};$('search').oninput=filter;$('categories').onclick=e=>{const b=e.target.closest('button');if(!b)return;selected=b.dataset.cat;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));filter();$('main').scrollIntoView({behavior:'smooth'})};
$('toggle').onclick=()=>{const hidden=document.body.classList.toggle('hidden-zh');$('toggle').textContent=hidden?'顯示中文':'隱藏中文';$('toggle').setAttribute('aria-pressed',String(hidden))};$('stop').onclick=stopReading;$('print').onclick=()=>window.print();
let activeSpeech=null;
function stopReading(){if('speechSynthesis' in window)speechSynthesis.cancel();activeSpeech=null;document.querySelectorAll('.speak').forEach(b=>{b.textContent='▶ 朗讀';b.setAttribute('aria-pressed','false')});$('speech-status').textContent='已停止朗讀';}
$('content').onclick=e=>{const b=e.target.closest('.speak');if(!b)return;if(!('speechSynthesis'in window)){ $('speech-status').textContent='此瀏覽器不支援朗讀，請使用 Edge、Chrome 或 Safari。';return}
stopReading();const u=new SpeechSynthesisUtterance(b.closest('.pair').querySelector('.en').textContent);u.lang='en-US';u.rate=Number($('rate').value);const voices=speechSynthesis.getVoices();const voice=voices.find(v=>v.lang==='en-US')||voices.find(v=>/^en[-_]/i.test(v.lang));if(voice)u.voice=voice;activeSpeech=u;b.textContent='◼ 朗讀中';b.setAttribute('aria-pressed','true');$('speech-status').textContent='正在朗讀英文…';
const finish=message=>{if(activeSpeech!==u)return;activeSpeech=null;b.textContent='▶ 朗讀';b.setAttribute('aria-pressed','false');$('speech-status').textContent=message};u.onend=()=>finish('朗讀完成');u.onerror=e=>finish(e.error==='canceled'||e.error==='interrupted'?'已停止朗讀':'無法播放英文，請確認裝置已安裝英文語音後再試。');speechSynthesis.speak(u)};

const id=location.hash.slice(1);if(data.some(x=>x.id===id))$('lesson').value=id;render();
