const $=id=>document.getElementById(id);let unit=UNITS[0],page=1,utterance=null;
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function stop(){if('speechSynthesis'in window)speechSynthesis.cancel();utterance=null;$('status').textContent='';document.querySelectorAll('.listen').forEach(b=>b.textContent='▶ 英文朗讀')}
function lessons(){const list=UNITS.filter(u=>u.book===$('book').value);$('lesson').innerHTML=list.map(u=>`<option value="${u.id}">${u.lesson} · ${escapeHTML(u.title)}</option>`).join('')}
function load(){stop();unit=UNITS.find(u=>u.id===$('lesson').value);page=1;$('page').innerHTML=Array.from({length:unit.pages},(_,i)=>`<option>${i+1}</option>`).join('');$('total').textContent=`／共 ${unit.pages} 頁`;$('pdf').href=`downloads/${unit.id}.pdf`;$('word').href=`downloads/${unit.id}.docx`;$('search').value='';showPage();paragraphs();history.replaceState(null,'','#'+unit.id)}
function showPage(){$('page').value=page;$('paper').src=`pages/${unit.id}-${page}.jpg`;$('paper').alt=`${unit.book} ${unit.lesson} ${unit.title} 教師版第 ${page} 頁`;$('prev').disabled=page===1;$('next').disabled=page===unit.pages;$('paper-scroll').scrollTop=0;const [w,h]=unit.sizes[page-1];$('paper').width=w;$('paper').height=h}
function english(text){return (text.match(/[A-Za-z0-9][A-Za-z0-9\s.,!?;:'"“”‘’()\-–—/…]*/g)||[]).filter(s=>/[A-Za-z]{2}/.test(s)).join(' ').trim()}
function paragraphs(){const q=$('search').value.trim().toLowerCase();const rows=unit.text.map((t,i)=>({t,i})).filter(({t})=>t.toLowerCase().includes(q));$('paragraphs').innerHTML=rows.map(({t,i})=>`<article class="paragraph"><p>${escapeHTML(t)}</p>${english(t)?`<button class="listen" data-index="${i}">▶ 英文朗讀</button>`:''}</article>`).join('')||'<p class="empty">找不到符合的文字。</p>'}
$('book').onchange=()=>{lessons();load()};$('lesson').onchange=load;$('page').onchange=()=>{page=Number($('page').value);showPage()};$('prev').onclick=()=>{if(page>1){page--;showPage()}};$('next').onclick=()=>{if(page<unit.pages){page++;showPage()}};$('zoom').onchange=()=>{$('paper').style.width=$('zoom').value==='fit'?'100%':$('zoom').value+'%';$('paper').style.maxWidth=$('zoom').value==='fit'?'':'none'};$('search').oninput=paragraphs;$('stop').onclick=stop;
$('text-toggle').onclick=()=>{const visible=$('reading').hidden;$('reading').hidden=!visible;document.body.classList.toggle('with-reading',visible);$('text-toggle').textContent=visible?'收起文字與朗讀':'開啟本課文字與朗讀';$('text-toggle').setAttribute('aria-pressed',String(visible));if(!visible)stop()};
$('paragraphs').onclick=e=>{const b=e.target.closest('.listen');if(!b)return;stop();if(!('speechSynthesis'in window)){$('status').textContent='此瀏覽器不支援朗讀，請使用 Edge 或 Chrome。';return}const u=new SpeechSynthesisUtterance(english(unit.text[Number(b.dataset.index)]));u.lang='en-US';u.rate=Number($('rate').value);const voice=speechSynthesis.getVoices().find(v=>/^en-US$/i.test(v.lang));if(voice)u.voice=voice;utterance=u;b.textContent='◼ 朗讀中';$('status').textContent='正在朗讀英文';const done=msg=>{if(utterance!==u)return;utterance=null;b.textContent='▶ 英文朗讀';$('status').textContent=msg};u.onend=()=>done('朗讀完成');u.onerror=()=>done('無法朗讀，請確認装置英文語音設定。');speechSynthesis.speak(u)};
const initial=UNITS.find(u=>u.id===location.hash.slice(1));if(initial)$('book').value=initial.book;lessons();if(initial)$('lesson').value=initial.id;load();
